name: Connect

on:
  workflow_dispatch:

env:
  RUST_LOG: info
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - name: Run all tests
        run: cargo build --release --bin dcutr-example

      - name: Connect
        run: target/release/dcutr-example --secret-key-seed 2 --mode dial --relay-address /ip4/107.170.193.89/tcp/4001/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN --remote-peer-id 12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X
