name: UPnP

on:
  workflow_dispatch:

env:
  RUST_LOG: info
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - name: Run all tests
        run: cargo build --release --bin upnp-example

      - name: Connect
        run: target/release/upnp-example
